name: elegant_toast_example
description: Example app for elegant_toast package.
version: 1.0.5

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  elegant_toast:
    path: ../

flutter:
  uses-material-design: true
